title: "vX.X.X Release"
labels: ["announcements"]
body:
  - type: markdown
    attributes:
      value: "**Copy this template for each release**"
  - type: textarea
    id: new-features
    attributes:
      label: "New Features"
      placeholder: |
        - Added: [Description]
        - Implemented: [Feature]
  - type: textarea
    id: fixes
    attributes:
      label: "Bug Fixes"
      placeholder: |
        - Fixed: [Issue #]
        - Resolved: [Bug Description]
  - type: textarea
    id: upgrade
    attributes:
      label: "Upgrade Notes"
      placeholder: "Backup your site before updating..."