categories:
  - id: question
    emoji: ":question:"
    name: Q&A
    description: Get help with configuration and troubleshooting
  - id: showcase
    emoji: ":art:"
    name: Showcase
    description: Share your implementations
  - id: ideas
    emoji: ":bulb:"
    name: Ideas
    description: Suggest new features
  - id: news
    emoji: ":loudspeaker:"
    name: Announcements
    description: Official plugin updates
  - id: integrations
    emoji: ":electric_plug:"
    name: Plugins & Themes
    description: Compatibility reports