title: "Q: [Your Question]"
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        **Before asking:**
        - [ ] Searched existing discussions
        - [ ] Checked the [FAQ](https://example.com/faq)
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Your system details"
      placeholder: |
        - WordPress: 
        - WooCommerce: 
        - PHP:
  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      placeholder: "Be specific..."