title: "Showcase: [Your Project Name]"
labels: ["showcase"]
body:
  - type: textarea
    id: url
    attributes:
      label: "Live Site URL"
      placeholder: "https://your-site.com"
      description: "Link to your live implementation"
  
  - type: textarea
    id: customizations
    attributes:
      label: "Customizations"
      placeholder: |
        - Modified templates: [list files]
        - Added CSS/JS: [describe changes]
      render: markdown
  
  # Image Upload Section
  - type: textarea
    attributes:
      label: "Upload screenshot"
      placeholder: "Upload your image by copy and pasting into this text box"
  
  - type: textarea
    id: technical-details
    attributes:
      label: "Technical Details (Optional)"
      placeholder: |
        ```php
        // Custom code snippets
        add_filter('pcl_grid_args', function($args) {
          return $args;
        });
        ```
      render: php
  
  - type: checkboxes
    id: permissions
    attributes:
      label: "Permissions"
      options:
        - label: "I allow my site to be featured in plugin demos"
        - label: "I consent to being contacted about this implementation"