title: "Showcase: [Project Name]"
labels: ["showcase"]
body:
  - type: textarea
    id: url
    attributes:
      label: "Live Site URL"
      placeholder: "https://"
  - type: textarea
    id: customizations
    attributes:
      label: "Customizations"
      placeholder: |
        - Modified: [Template Name]
        - Added: [Custom CSS/JS]
  - type: markdown
    attributes:
      value: "**Before/After Screenshots**"
  - type: textarea
    id: code
    attributes:
      label: "Code Snippets (Optional)"
      render: php