name: Issue Validation
on:
  issues:
    types: [opened]

jobs:
  check-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            if (issue.body.length < 50) {
              github.rest.issues.createComment({
                issue_number: issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "⚠️ Please provide more details using our [issue template]()"
              });
            }